
---

- name: Backup Cisco Router or Switch
  connection: network_cli
  hosts: Cisco_Network_Backup
  gather_facts: 

  tasks:
    - name: Accespt ansible net hostname
      ios_facts: 
        gather_subset: all

    - name: Get current date
      local_action: command date +%Y-%b-%d
      register: date
    
    - name: Get current time
      local_action: command date +%H:%M
      register: time      

    - name: Get running-config and save it
      ios_config:
       backup: yes
      register: backup_config
   
    - name: Store the config to directory      
      copy:
       src: "{{ backup_config.backup_path }}"
       dest: "/tmp/backups/{{ inventory_hostname }}.txt"     

       #- name: Tasks done
       #debug: msg="All tasks has been done on {{ date.stdout }} at {{ time.stdout }}."

